USE [master]
GO

/****** Object:  Database [PersonalPortal]    Script Date: 19/12/2019 02:09:11 p. m. ******/
DROP DATABASE IF EXISTS [PersonalPortal]

CREATE DATABASE [PersonalPortal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PersonalPortal', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PersonalPortal.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PersonalPortal_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PersonalPortal_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PersonalPortal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PersonalPortal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PersonalPortal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PersonalPortal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PersonalPortal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PersonalPortal] SET ARITHABORT OFF 
GO

ALTER DATABASE [PersonalPortal] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PersonalPortal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PersonalPortal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PersonalPortal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PersonalPortal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PersonalPortal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PersonalPortal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PersonalPortal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PersonalPortal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PersonalPortal] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PersonalPortal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PersonalPortal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PersonalPortal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PersonalPortal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PersonalPortal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PersonalPortal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PersonalPortal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PersonalPortal] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PersonalPortal] SET  MULTI_USER 
GO

ALTER DATABASE [PersonalPortal] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PersonalPortal] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PersonalPortal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PersonalPortal] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PersonalPortal] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PersonalPortal] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PersonalPortal] SET  READ_WRITE 
GO