USE [master]
GO

/****** Object:  Database [PersonalPortal]    Script Date: 19/12/2019 02:09:11 p. m. ******/
DROP DATABASE IF EXISTS [PersonalPortal]

CREATE DATABASE [PersonalPortal] 
GO

ALTER DATABASE [PersonalPortal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PersonalPortal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PersonalPortal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PersonalPortal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PersonalPortal] SET ARITHABORT OFF 
GO

ALTER DATABASE [PersonalPortal] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PersonalPortal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PersonalPortal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PersonalPortal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PersonalPortal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PersonalPortal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PersonalPortal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PersonalPortal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PersonalPortal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PersonalPortal] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PersonalPortal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PersonalPortal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PersonalPortal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PersonalPortal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PersonalPortal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PersonalPortal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PersonalPortal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PersonalPortal] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PersonalPortal] SET  MULTI_USER 
GO

ALTER DATABASE [PersonalPortal] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PersonalPortal] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PersonalPortal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PersonalPortal] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PersonalPortal] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PersonalPortal] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PersonalPortal] SET  READ_WRITE 
GO